In [39]:
import pandas as pd
import numpy as np

In [40]:
df1 = pd.read_csv("CSV_1.csv")

In [41]:
df1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,8.318680e+11,9.780760e+11,1.020960e+12,1.018710e+12,9.386080e+11,1.114140e+12,1.228970e+12,1.179360e+12,1.242690e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,7.000280e+11,6.940510e+11,7.778400e+11,1.027000e+12,9.637850e+11,1.026650e+12,1.063650e+12,9.382380e+11,7.363850e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312120e+11,1.071680e+11,1.009990e+11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.682677e+09,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,3.235860e+11,3.814490e+11,4.052610e+11,3.893300e+11,3.379750e+11,4.199860e+11,4.075960e+11,3.814410e+11,4.011450e+11,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,...,2.095841e+10,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,...,2.055925e+10,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,NaN

In [42]:
df1 = df1.fillna(0)
df1 = df1.drop_duplicates()
df1 = df1.drop(columns = ['Indicator Name', 'Indicator Code','2025'])

In [43]:
df1

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.962907e+09,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09
1,Africa Eastern and Southern,AFE,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,3.692725e+10,3.844416e+10,...,9.100020e+11,8.318680e+11,9.780760e+11,1.020960e+12,1.018710e+12,9.386080e+11,1.114140e+12,1.228970e+12,1.179360e+12,1.242690e+12
2,Afghanistan,AFG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,0.000000e+00
3,Africa Western and Central,AFW,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,1.803395e+10,1.649354e+10,...,7.780220e+11,7.000280e+11,6.940510e+11,7.778400e+11,1.027000e+12,9.637850e+11,1.026650e+12,1.063650e+12,9.382380e+11,7.363850e+11
4,Angola,AGO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.025430e+11,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312120e+11,1.071680e+11,1.009990e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.295848e+09,6.682677e+09,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10
262,"Yemen, Rep.",YEM,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,4.244449e+10,3.131783e+10,2.684223e+10,2.160616e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
263,South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,3.467100e+11,3.235860e+11,3.814490e+11,4.052610e+11,3.893300e+11,3.379750e+11,4.199860e+11,4.075960e+11,3.814410e+11,4.011450e+11
264,Zambia,ZMB,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,1.239000e+09,1.340639e+09,...,2.125122e+10,2.095841e+10,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10
265,Zimbabwe,ZWE,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,1.282404e+09,1.397715e+09,...,1.997325e+10,2.055925e+10,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10

In [44]:
df2 = pd.read_csv("CSV_2.csv")

In [45]:
df2

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan,NaN
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN
...,...,...,...,...,...,...
260,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo,NaN
261,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep.",NaN
262,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa,NaN
263,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia,NaN
264,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe,NaN

In [46]:
df2 = df2.drop_duplicates()

In [47]:
df2

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan,NaN
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN
...,...,...,...,...,...,...
260,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo,NaN
261,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep.",NaN
262,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa,NaN
263,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia,NaN
264,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe,NaN

In [48]:
df2 = df2.drop(columns = ['Unnamed: 5'])

In [49]:
df2 = df2.fillna("NA")

In [50]:
df2

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NA,Aruba
1,AFE,NA,NA,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NA,NA,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
260,XKX,Europe & Central Asia,Upper middle income,NA,Kosovo
261,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
262,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
263,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
264,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [51]:
df2.set_index('TableName', inplace=True)

In [52]:
df2

,Country Code,Region,IncomeGroup,SpecialNotes
TableName,,,,
Aruba,ABW,Latin America & Caribbean,High income,NA
Africa Eastern and Southern,AFE,NA,NA,"26 countries, stretching from the Red Sea in t..."
Afghanistan,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...
Africa Western and Central,AFW,NA,NA,"22 countries, stretching from the westernmost ..."
Angola,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
...,...,...,...,...
Kosovo,XKX,Europe & Central Asia,Upper middle income,NA
"Yemen, Rep.",YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
South Africa,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
Zambia,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [57]:
df3 = pd.merge(df1, df2, on = 'Country Code')

In [58]:
df3

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup,SpecialNotes
0,Aruba,ABW,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,Latin America & Caribbean,High income,NA
1,Africa Eastern and Southern,AFE,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,3.692725e+10,3.844416e+10,...,1.020960e+12,1.018710e+12,9.386080e+11,1.114140e+12,1.228970e+12,1.179360e+12,1.242690e+12,NA,NA,"26 countries, stretching from the Red Sea in t..."
2,Afghanistan,AFG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,0.000000e+00,Middle East & North Africa,Low income,The reporting period for national accounts dat...
3,Africa Western and Central,AFW,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,1.803395e+10,1.649354e+10,...,7.778400e+11,1.027000e+12,9.637850e+11,1.026650e+12,1.063650e+12,9.382380e+11,7.363850e+11,NA,NA,"22 countries, stretching from the westernmost ..."
4,Angola,AGO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312120e+11,1.071680e+11,1.009990e+11,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,Europe & Central Asia,Upper middle income,NA
261,"Yemen, Rep.",YEM,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.160616e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
262,South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.052610e+11,3.893300e+11,3.379750e+11,4.199860e+11,4.075960e+11,3.814410e+11,4.011450e+11,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
263,Zambia,ZMB,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,1.239000e+09,1.340639e+09,...,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
264,Zimbabwe,ZWE,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,1.282404e+09,1.397715e+09,...,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [59]:
df3.drop_duplicates(inplace=True)

In [60]:
df3

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup,SpecialNotes
0,Aruba,ABW,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,Latin America & Caribbean,High income,NA
1,Africa Eastern and Southern,AFE,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,3.692725e+10,3.844416e+10,...,1.020960e+12,1.018710e+12,9.386080e+11,1.114140e+12,1.228970e+12,1.179360e+12,1.242690e+12,NA,NA,"26 countries, stretching from the Red Sea in t..."
2,Afghanistan,AFG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,0.000000e+00,Middle East & North Africa,Low income,The reporting period for national accounts dat...
3,Africa Western and Central,AFW,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,1.803395e+10,1.649354e+10,...,7.778400e+11,1.027000e+12,9.637850e+11,1.026650e+12,1.063650e+12,9.382380e+11,7.363850e+11,NA,NA,"22 countries, stretching from the westernmost ..."
4,Angola,AGO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312120e+11,1.071680e+11,1.009990e+11,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,Europe & Central Asia,Upper middle income,NA
261,"Yemen, Rep.",YEM,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.160616e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
262,South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.052610e+11,3.893300e+11,3.379750e+11,4.199860e+11,4.075960e+11,3.814410e+11,4.011450e+11,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
263,Zambia,ZMB,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,1.239000e+09,1.340639e+09,...,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
264,Zimbabwe,ZWE,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,1.282404e+09,1.397715e+09,...,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [63]:
df3.set_index('Country Name', inplace=True)

In [64]:
df3

,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup,SpecialNotes
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,Latin America & Caribbean,High income,NA
Africa Eastern and Southern,AFE,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,3.692725e+10,3.844416e+10,4.174200e+10,...,1.020960e+12,1.018710e+12,9.386080e+11,1.114140e+12,1.228970e+12,1.179360e+12,1.242690e+12,NA,NA,"26 countries, stretching from the Red Sea in t..."
Afghanistan,AFG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,0.000000e+00,Middle East & North Africa,Low income,The reporting period for national accounts dat...
Africa Western and Central,AFW,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,1.803395e+10,1.649354e+10,1.702260e+10,...,7.778400e+11,1.027000e+12,9.637850e+11,1.026650e+12,1.063650e+12,9.382380e+11,7.363850e+11,NA,NA,"22 countries, stretching from the westernmost ..."
Angola,AGO,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312120e+11,1.071680e+11,1.009990e+11,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,Europe & Central Asia,Upper middle income,NA
"Yemen, Rep.",YEM,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.160616e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,1.712479e+10,...,4.052610e+11,3.893300e+11,3.379750e+11,4.199860e+11,4.075960e+11,3.814410e+11,4.011450e+11,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
Zambia,ZMB,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,1.239000e+09,1.340639e+09,1.573739e+09,...,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
Zimbabwe,ZWE,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,1.282404e+09,1.397715e+09,1.480355e+09,...,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [67]:
drop_columns = df3.loc[:,"1960":"1989"]
df3.drop(columns = drop_columns, inplace=True)

In [68]:
df3

,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup,SpecialNotes
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,7.648045e+08,8.720670e+08,9.586592e+08,1.083240e+09,1.245810e+09,1.320670e+09,1.379888e+09,1.531844e+09,1.665363e+09,...,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,Latin America & Caribbean,High income,NA
Africa Eastern and Southern,AFE,2.563830e+11,2.769190e+11,2.411880e+11,2.399810e+11,2.434780e+11,2.733270e+11,2.734280e+11,2.882710e+11,2.687280e+11,...,1.020960e+12,1.018710e+12,9.386080e+11,1.114140e+12,1.228970e+12,1.179360e+12,1.242690e+12,NA,NA,"26 countries, stretching from the Red Sea in t..."
Afghanistan,AFG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,0.000000e+00,Middle East & North Africa,Low income,The reporting period for national accounts dat...
Africa Western and Central,AFW,1.242780e+11,1.307940e+11,1.254490e+11,1.305470e+11,1.353510e+11,2.078440e+11,2.635640e+11,2.764600e+11,2.971270e+11,...,7.778400e+11,1.027000e+12,9.637850e+11,1.026650e+12,1.063650e+12,9.382380e+11,7.363850e+11,NA,NA,"22 countries, stretching from the westernmost ..."
Angola,AGO,1.122952e+10,1.060378e+10,8.307811e+09,5.768720e+09,4.438321e+09,5.538749e+09,7.526422e+09,7.648380e+09,6.506222e+09,...,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312120e+11,1.071680e+11,1.009990e+11,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,Europe & Central Asia,Upper middle income,NA
"Yemen, Rep.",YEM,1.264382e+10,1.466545e+10,1.795937e+10,2.173680e+10,2.801948e+10,1.279635e+10,6.496164e+09,6.838299e+09,6.322176e+09,...,2.160616e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
South Africa,ZAF,1.260480e+11,1.352040e+11,1.469560e+11,1.471950e+11,1.535130e+11,1.717360e+11,1.632350e+11,1.689780e+11,1.529830e+11,...,4.052610e+11,3.893300e+11,3.379750e+11,4.199860e+11,4.075960e+11,3.814410e+11,4.011450e+11,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
Zambia,ZMB,3.288382e+09,3.376807e+09,3.182811e+09,3.273505e+09,3.656806e+09,3.806983e+09,3.597221e+09,4.303288e+09,3.537742e+09,...,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
Zimbabwe,ZWE,8.788302e+09,8.646000e+09,6.755000e+09,6.567250e+09,6.894250e+09,7.115000e+09,8.557500e+09,8.534000e+09,6.405250e+09,...,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [84]:
df3[df3.select_dtypes(include='float64').columns] = df3.select_dtypes(include='float64').astype(int)

In [85]:
df3

,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup,SpecialNotes
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,764804469,872067039,958659217,1083240223,1245810056,1320670391,1379888268,1531843575,1665363128,...,3276187709,3346623191,2471419182,2880902799,3324034443,3834729616,4265650673,Latin America & Caribbean,High income,NA
Africa Eastern and Southern,AFE,256383000000,276919000000,241188000000,239981000000,243478000000,273327000000,273428000000,288271000000,268728000000,...,1020960000000,1018710000000,938608000000,1114140000000,1228970000000,1179360000000,1242690000000,NA,NA,"26 countries, stretching from the Red Sea in t..."
Afghanistan,AFG,0,0,0,0,0,0,0,0,0,...,18053222687,18799444490,19955929052,14259995441,14497243872,17152234637,0,Middle East & North Africa,Low income,The reporting period for national accounts dat...
Africa Western and Central,AFW,124278000000,130794000000,125449000000,130547000000,135351000000,207844000000,263564000000,276460000000,297127000000,...,777840000000,1027000000000,963785000000,1026650000000,1063650000000,938238000000,736385000000,NA,NA,"22 countries, stretching from the westernmost ..."
Angola,AGO,11229515599,10603784541,8307810974,5768720422,4438321017,5538749260,7526421519,7648380196,6506221616,...,89512794227,80734428593,58852456454,79559543805,131212000000,107168000000,100999000000,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,0,0,0,0,0,0,0,0,0,...,7878762812,7899741279,7717143396,9413408574,9354907646,10468224575,11197246323,Europe & Central Asia,Upper middle income,NA
"Yemen, Rep.",YEM,12643821569,14665445462,17959367194,21736802664,28019483764,12796345679,6496163616,6838298531,6322175566,...,21606160663,0,0,0,0,0,0,Middle East & North Africa,Low income,The World Bank systematically assesses the app...
South Africa,ZAF,126048000000,135204000000,146956000000,147195000000,153513000000,171736000000,163235000000,168978000000,152983000000,...,405261000000,389330000000,337975000000,419986000000,407596000000,381441000000,401145000000,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
Zambia,ZMB,3288381797,3376806697,3182810841,3273505344,3656806166,3806983413,3597220962,4303288480,3537741942,...,26311507274,23308667781,18137764931,22096416932,29163782140,27577956471,25303185342,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...
Zimbabwe,ZWE,8788301546,8646000000,6755000000,6567250000,6894250000,7115000000,8557500000,8534000000,6405250000,...,34141666667,33357695635,31980334561,41287673690,40757561709,35871779681,41539411516,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...

In [86]:
df3.drop(columns = ['SpecialNotes', 'Region'], inplace=True)

In [87]:
df3

,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,IncomeGroup
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,764804469,872067039,958659217,1083240223,1245810056,1320670391,1379888268,1531843575,1665363128,...,2983637430,3092427933,3276187709,3346623191,2471419182,2880902799,3324034443,3834729616,4265650673,High income
Africa Eastern and Southern,AFE,256383000000,276919000000,241188000000,239981000000,243478000000,273327000000,273428000000,288271000000,268728000000,...,831868000000,978076000000,1020960000000,1018710000000,938608000000,1114140000000,1228970000000,1179360000000,1242690000000,NA
Afghanistan,AFG,0,0,0,0,0,0,0,0,0,...,18116572395,18753456498,18053222687,18799444490,19955929052,14259995441,14497243872,17152234637,0,Low income
Africa Western and Central,AFW,124278000000,130794000000,125449000000,130547000000,135351000000,207844000000,263564000000,276460000000,297127000000,...,700028000000,694051000000,777840000000,1027000000000,963785000000,1026650000000,1063650000000,938238000000,736385000000,NA
Angola,AGO,11229515599,10603784541,8307810974,5768720422,4438321017,5538749260,7526421519,7648380196,6506221616,...,59878249719,84376935689,89512794227,80734428593,58852456454,79559543805,131212000000,107168000000,100999000000,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,XKX,0,0,0,0,0,0,0,0,0,...,6682677290,7180768692,7878762812,7899741279,7717143396,9413408574,9354907646,10468224575,11197246323,Upper middle income
"Yemen, Rep.",YEM,12643821569,14665445462,17959367194,21736802664,28019483764,12796345679,6496163616,6838298531,6322175566,...,31317825274,26842229045,21606160663,0,0,0,0,0,0,Low income
South Africa,ZAF,126048000000,135204000000,146956000000,147195000000,153513000000,171736000000,163235000000,168978000000,152983000000,...,323586000000,381449000000,405261000000,389330000000,337975000000,419986000000,407596000000,381441000000,401145000000,Upper middle income
Zambia,ZMB,3288381797,3376806697,3182810841,3273505344,3656806166,3806983413,3597220962,4303288480,3537741942,...,20958412538,25873601261,26311507274,23308667781,18137764931,22096416932,29163782140,27577956471,25303185342,Lower middle income
Zimbabwe,ZWE,8788301546,8646000000,6755000000,6567250000,6894250000,7115000000,8557500000,8534000000,6405250000,...,20559250000,51035657371,34141666667,33357695635,31980334561,41287673690,40757561709,35871779681,41539411516,Lower middle income

In [92]:
df3.to_csv('GDP.csv', index=True)

In [93]:
df4 = pd.read_csv('CSV_4.csv')

In [94]:
df4

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.446877,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691,11.580510,4.944324,1.619450,NaN
262,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288877,2.102351,1.246275,1.337971,2.534989,4.069019,...,6.602908,5.186187,4.509873,4.102851,3.232388,4.618745,7.039873,6.075244,4.361152,NaN
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,17.869730,6.577312,7.494572,9.150316,15.733060,22.020768,10.993204,10.884532,14.985626,NaN
265,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105,104.705171,NaN,NaN,NaN

In [96]:
df4 = df4.fillna(0)
df4.drop(columns = ['Indicator Name', 'Indicator Code', '2025'], inplace=True)
df4.drop(columns = [str(year) for year in range(1960, 1990)], inplace=True)

In [97]:
df4

,Country Name,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,5.836688,5.555556,3.873375,5.215560,6.311080,3.361391,3.225288,2.999948,...,0.474764,-0.931196,-1.028282,3.626041,4.257462,0.000000,0.000000,0.000000,0.000000,0.000000
1,Africa Eastern and Southern,AFE,12.457914,17.678100,16.167612,13.135661,14.852815,12.288591,9.706586,10.249599,...,5.098562,6.446877,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857
2,Afghanistan,AFG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.661709,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186
3,Africa Western and Central,AFW,1.057361,1.741888,-0.062999,0.553456,31.841017,10.563289,4.914240,3.997142,...,2.130817,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044
4,Angola,AGO,0.000000,83.783784,299.509804,1378.527607,949.792531,2666.450593,4145.105982,219.176721,...,9.355972,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.536929,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691,11.580510,4.944324,1.619450
262,"Yemen, Rep.",YEM,0.000000,36.000000,29.411765,35.752298,49.394155,55.081107,30.733733,2.176727,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
263,South Africa,ZAF,14.320992,15.334779,13.874704,9.717427,8.938564,8.680424,7.354120,8.597776,...,4.518691,6.602908,5.186187,4.509873,4.102851,3.232388,4.618745,7.039873,6.075244,4.361152
264,Zambia,ZMB,107.023809,97.642323,165.706527,183.312041,54.601322,34.929587,43.073098,24.418722,...,10.110593,17.869730,6.577312,7.494572,9.150316,15.733060,22.020768,10.993204,10.884532,14.985626
265,Zimbabwe,ZWE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-2.430968,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105,104.705171,0.000000,0.000000

In [101]:
df4.drop_duplicates(inplace=True)
df4.set_index('Country Name', inplace=True)
df4.to_csv('Inflation.csv', index=True)

In [103]:
df5 = pd.read_csv('CSV_6.csv')

In [104]:
df5

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.074429,7.214915,7.244843,7.459106,7.974302,8.407412,7.869470,7.676548,7.571697,7.539234
2,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.116000,11.184000,11.192000,11.187000,11.710000,12.006000,14.100000,14.008000,13.687000,13.351000
3,Africa Western and Central,AFW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.167580,4.283996,4.334377,4.390764,4.795318,4.666634,3.593354,3.200801,3.172421,3.190552
4,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.572000,16.617000,16.602000,16.497000,16.696000,15.799000,14.124000,14.051000,14.020000,14.108000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.420000,18.611000,17.593000,17.213000,17.963000,18.312000,17.224000,16.944000,16.970000,17.322000
263,South Africa,ZAF,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,26.536000,27.035000,26.906000,28.468000,29.217000,34.007000,33.268000,32.098000,32.279000,32.391000
264,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.244000,4.529000,5.032000,5.538000,6.032000,5.197000,5.993000,5.861000,5.898000,5.918000
265,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.896000,6.350000,6.788000,7.373000,8.617000,9.540000,10.087000,9.348000,9.435000,9.293000

In [106]:
df5 = df5.fillna(0)
df5.drop(columns = ['Indicator Name', 'Indicator Code'], inplace=True)
df5.drop(columns = [str(year) for year in range(1960, 1990)], inplace=True)
df5.drop_duplicates(inplace=True)
df5.set_index('Country Name', inplace=True)
df5.to_csv('Unemployment.csv', index=True)